name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.11]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install packages
        run: make install
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: format
        run: make format
      - name: Build status badge - Strategy ${{ matrix.python-version }} on ${{ matrix.os }}
        uses: RubbaBoy/BYOB@v1.3.0
        with:
          NAME: "Build Status - Strategy ${{ matrix.python-version }} on ${{ matrix.os }}"
          LABEL: "Build Status - Strategy ${{ matrix.python-version }} on ${{ matrix.os }}"
          STATUS: ${{ job.status }}
          COLOR: ${{ job.status == 'success' && 'green' || job.status == 'failure' && 'red' || 'yellow' }}
          OUTPUT_FILE: "badge-strategy-${{ matrix.python-version }}-${{ matrix.os }}.svg"
