name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9, 3.11]
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: install packages
        run: make install
      - name: lint
        run: make lint
      - name: test
        run: make test
      - name: format  
        run: make format
      - name: Generate Badge URL
        id: generate_badge
        run: echo "::set-output name=badge_url::https://img.shields.io/badge/Build-${{ matrix.os }}_${{ matrix.python-version }}-brightgreen"
      - name: Upload Badge
        uses: actions/upload-artifact@v2
        with:
            name: ${{ matrix.os }} ${{ matrix.python-version }}
            path: *.svg